# **Atividade IV - Data Mining e Machine Learning**

**Descrição:** Script de preparação do arquivo `base_preparada.arff`

## **1 Importação de Bibliotecas**

In [1]:
# Importando as bibliotecas necessárias
import pandas as pd

print("Bibliotecas importadas com sucesso!")

Bibliotecas importadas com sucesso!

## **2 Importação da Base de Dados**

In [2]:
# Caminho do arquivo CSV
CAMINHO_ARQUIVO = r"..\data\base_tratada.csv"
print("Caminho do arquivo CSV definido")

Caminho do arquivo CSV definido

In [3]:
# Criando o DataFrame Inicial (p/ visulização) a partir do arquivo CSV
df = pd.read_csv(CAMINHO_ARQUIVO, encoding='utf-8')
print("DataFrame Inicial criado com sucesso")

# Visualização do DataFrame Inicial
print("\nExibindo as cinco primeiras linhas do DataFrame Inicial")
df.head()

DataFrame Inicial criado com sucesso

Exibindo as cinco primeiras linhas do DataFrame Inicial

,EstacaoCodigo,NivelConsistencia,Data,TipoMedicaoChuvas,Maxima,Total,DiaMaxima,NumDiasDeChuva,Chuva01,Chuva02,...,Chuva26,Chuva27,Chuva28,Chuva29,Chuva30,Chuva31,Estacao,NumDiasSemChuva,Classificacao_Chuva,Ano
0,469001,1,2025-12-01,1,190.3,498.6,2.0,25,32.5,190.3,...,5.0,20.3,8.0,2.7,6.7,0.0,Verão,6,Muito Chuvoso,2025
1,469001,1,2025-11-01,1,112.5,330.3,23.0,17,0.0,0.0,...,0.0,13.1,33.4,8.2,20.5,NaN,Primavera,13,Muito Chuvoso,2025
2,469001,1,2025-10-01,1,33.5,205.2,1.0,20,33.5,1.3,...,2.0,0.0,12.5,5.2,12.4,1.1,Primavera,11,Normal,2025
3,469001,1,2025-09-01,1,66.5,264.0,26.0,16,34.8,0.4,...,66.5,0.0,0.0,16.0,16.2,NaN,Primavera,14,Normal,2025
4,469001,1,2025-08-01,1,39.0,82.0,6.0,10,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Inverno,21,Muito Seco,2025

## **3 Preparação da Base de Dados p/ Weka**

In [4]:
# Definição das colunas essenciais de trabalho
sel_atributos = ['Ano', 'Maxima', 'Total', 'NumDiasDeChuva', 'NumDiasSemChuva', 'Estacao', 'Classificacao_Chuva']
print("Atributos selecionados com sucesso")

# Criação do DataFrame Weka
df_weka = df[sel_atributos].copy()
print("\nDataFrame Weka criado com sucesso")

Atributos selecionados com sucesso

DataFrame Weka criado com sucesso

In [5]:
# Ajustes de Tipo e Valores
print("Ajustes")
df_weka['Estacao'] = df_weka['Estacao'].replace({'Verão': 'Verao'})
print("   - Valores de 'Estacao' ajustados")

df_weka['Classificacao_Chuva'] = df_weka['Classificacao_Chuva'].replace({
    'Muito Chuvoso': 'MuitoChuvoso',
    'Muito Seco': 'MuitoSeco'
})
print("   - Valores de 'Classificacao_Chuva' ajustados")

Ajustes
   - Valores de 'Estacao' ajustados
   - Valores de 'Classificacao_Chuva' ajustados

In [6]:
# Visualização do DataFrame Weka
print("Exibindo as cinco primeiras linhas do DataFrame Weka")
df_weka.head()

Exibindo as cinco primeiras linhas do DataFrame Weka

,Ano,Maxima,Total,NumDiasDeChuva,NumDiasSemChuva,Estacao,Classificacao_Chuva
0,2025,190.3,498.6,25,6,Verao,MuitoChuvoso
1,2025,112.5,330.3,17,13,Primavera,MuitoChuvoso
2,2025,33.5,205.2,20,11,Primavera,Normal
3,2025,66.5,264.0,16,14,Primavera,Normal
4,2025,39.0,82.0,10,21,Inverno,MuitoSeco

## **4 Exportação da Base de Dados p/ Weka**

In [7]:
# Definição do caminho e nome do arquivo Weka
CAMINHO_ARQUIVO_WEKA = "../data/base_preparada.arff"
print("Caminho e nome da base Weka definidos com sucesso")

Caminho e nome da base Weka definidos com sucesso

In [8]:
# Criação do arquivo ARFF
with open(CAMINHO_ARQUIVO_WEKA, 'w') as f:
    f.write('@RELATION precipitacao_tabatinga\n\n')

    f.write('@ATTRIBUTE Ano NUMERIC\n')
    f.write('@ATTRIBUTE Maxima NUMERIC\n')
    f.write('@ATTRIBUTE Total NUMERIC\n')
    f.write('@ATTRIBUTE NumDiasDeChuva NUMERIC\n')
    f.write('@ATTRIBUTE NumDiasSemChuva NUMERIC\n')
    f.write('@ATTRIBUTE Estacao {Verao,Outono,Inverno,Primavera}\n')
    f.write('@ATTRIBUTE Classificacao_Chuva {MuitoChuvoso,Normal,MuitoSeco}\n')

    f.write('\n@DATA\n')

    for _, row in df_weka.iterrows():
        linha = f"{row['Ano']},{row['Maxima']},{row['Total']},{row['NumDiasDeChuva']},{row['NumDiasSemChuva']},{row['Estacao']},{row['Classificacao_Chuva']}\n"
        f.write(linha)

print(f"Arquivo ARFF gerado com sucesso em: {CAMINHO_ARQUIVO_WEKA}")

Arquivo ARFF gerado com sucesso em: ../data/base_preparada.arff